config/routes.rb
# == Route Map
#
#                     Prefix Verb   URI Pattern                              Controller#Action
#                  user_root GET    /                                        users/dashboard#index
#                 admin_root GET    /                                        admins/dashboard#index
#                       root GET    /                                        landings#index
#           new_user_session GET    /users/sign_in(.:format)                 users/sessions#new
#               user_session POST   /users/sign_in(.:format)                 users/sessions#create
#       destroy_user_session DELETE /users/sign_out(.:format)                users/sessions#destroy
#          new_user_password GET    /users/password/new(.:format)            devise/passwords#new
#         edit_user_password GET    /users/password/edit(.:format)           devise/passwords#edit
#              user_password PATCH  /users/password(.:format)                devise/passwords#update
#                            PUT    /users/password(.:format)                devise/passwords#update
#                            POST   /users/password(.:format)                devise/passwords#create
#   cancel_user_registration GET    /users/cancel(.:format)                  users/registrations#cancel
#      new_user_registration GET    /users/sign_up(.:format)                 users/registrations#new
#     edit_user_registration GET    /users/edit(.:format)                    users/registrations#edit
#          user_registration PATCH  /users(.:format)                         users/registrations#update
#                            PUT    /users(.:format)                         users/registrations#update
#                            DELETE /users(.:format)                         users/registrations#destroy
#                            POST   /users(.:format)                         users/registrations#create
#      new_user_confirmation GET    /users/confirmation/new(.:format)        devise/confirmations#new
#          user_confirmation GET    /users/confirmation(.:format)            devise/confirmations#show
#                            POST   /users/confirmation(.:format)            devise/confirmations#create
#          new_admin_session GET    /admins/sign_in(.:format)                admins/sessions#new
#              admin_session POST   /admins/sign_in(.:format)                admins/sessions#create
#      destroy_admin_session DELETE /admins/sign_out(.:format)               admins/sessions#destroy
#         new_admin_password GET    /admins/password/new(.:format)           admins/passwords#new
#        edit_admin_password GET    /admins/password/edit(.:format)          admins/passwords#edit
#             admin_password PATCH  /admins/password(.:format)               admins/passwords#update
#                            PUT    /admins/password(.:format)               admins/passwords#update
#                            POST   /admins/password(.:format)               admins/passwords#create
#  cancel_admin_registration GET    /admins/cancel(.:format)                 devise/registrations#cancel
#     new_admin_registration GET    /admins/sign_up(.:format)                devise/registrations#new
#    edit_admin_registration GET    /admins/edit(.:format)                   devise/registrations#edit
#         admin_registration PATCH  /admins(.:format)                        devise/registrations#update
#                            PUT    /admins(.:format)                        devise/registrations#update
#                            DELETE /admins(.:format)                        devise/registrations#destroy
#                            POST   /admins(.:format)                        devise/registrations#create
#     admins_dashboard_index GET    /admins/dashboard(.:format)              admins/dashboard#index
#                            POST   /admins/dashboard(.:format)              admins/dashboard#create
#       new_admins_dashboard GET    /admins/dashboard/new(.:format)          admins/dashboard#new
#      edit_admins_dashboard GET    /admins/dashboard/:id/edit(.:format)     admins/dashboard#edit
#           admins_dashboard GET    /admins/dashboard/:id(.:format)          admins/dashboard#show
#                            PATCH  /admins/dashboard/:id(.:format)          admins/dashboard#update
#                            PUT    /admins/dashboard/:id(.:format)          admins/dashboard#update
#                            DELETE /admins/dashboard/:id(.:format)          admins/dashboard#destroy
#      users_dashboard_index GET    /users/dashboard(.:format)               users/dashboard#index
#                            POST   /users/dashboard(.:format)               users/dashboard#create
#        new_users_dashboard GET    /users/dashboard/new(.:format)           users/dashboard#new
#       edit_users_dashboard GET    /users/dashboard/:id/edit(.:format)      users/dashboard#edit
#            users_dashboard GET    /users/dashboard/:id(.:format)           users/dashboard#show
#                            PATCH  /users/dashboard/:id(.:format)           users/dashboard#update
#                            PUT    /users/dashboard/:id(.:format)           users/dashboard#update
#                            DELETE /users/dashboard/:id(.:format)           users/dashboard#destroy
#                     scores GET    /scores(.:format)                        scores#index
#                            POST   /scores(.:format)                        scores#create
#                  new_score GET    /scores/new(.:format)                    scores#new
#                 edit_score GET    /scores/:id/edit(.:format)               scores#edit
#                      score GET    /scores/:id(.:format)                    scores#show
#                            PATCH  /scores/:id(.:format)                    scores#update
#                            PUT    /scores/:id(.:format)                    scores#update
#                            DELETE /scores/:id(.:format)                    scores#destroy
# present_confirmation_index GET    /confirmations(.:format)                 confirmations#index
#                            POST   /confirmations(.:format)                 confirmations#create
#   new_present_confirmation GET    /confirmations/new(.:format)             confirmations#new
#  edit_present_confirmation GET    /confirmations/:id/edit(.:format)        confirmations#edit
#       present_confirmation GET    /confirmations/:id(.:format)             confirmations#show
#                            PATCH  /confirmations/:id(.:format)             confirmations#update
#                            PUT    /confirmations/:id(.:format)             confirmations#update
#                            DELETE /confirmations/:id(.:format)             confirmations#destroy
#               bipa_courses GET    /bipa_courses(.:format)                  bipa_courses#index
#                            POST   /bipa_courses(.:format)                  bipa_courses#create
#            new_bipa_course GET    /bipa_courses/new(.:format)              bipa_courses#new
#           edit_bipa_course GET    /bipa_courses/:id/edit(.:format)         bipa_courses#edit
#                bipa_course GET    /bipa_courses/:id(.:format)              bipa_courses#show
#                            PATCH  /bipa_courses/:id(.:format)              bipa_courses#update
#                            PUT    /bipa_courses/:id(.:format)              bipa_courses#update
#                            DELETE /bipa_courses/:id(.:format)              bipa_courses#destroy
#              to_indonesias GET    /to_indonesias(.:format)                 to_indonesias#index
#                            POST   /to_indonesias(.:format)                 to_indonesias#create
#           new_to_indonesia GET    /to_indonesias/new(.:format)             to_indonesias#new
#          edit_to_indonesia GET    /to_indonesias/:id/edit(.:format)        to_indonesias#edit
#               to_indonesia GET    /to_indonesias/:id(.:format)             to_indonesias#show
#                            PATCH  /to_indonesias/:id(.:format)             to_indonesias#update
#                            PUT    /to_indonesias/:id(.:format)             to_indonesias#update
#                            DELETE /to_indonesias/:id(.:format)             to_indonesias#destroy
#                  schedules GET    /schedules(.:format)                     schedules#index
#                            POST   /schedules(.:format)                     schedules#create
#               new_schedule GET    /schedules/new(.:format)                 schedules#new
#              edit_schedule GET    /schedules/:id/edit(.:format)            schedules#edit
#                   schedule GET    /schedules/:id(.:format)                 schedules#show
#                            PATCH  /schedules/:id(.:format)                 schedules#update
#                            PUT    /schedules/:id(.:format)                 schedules#update
#                            DELETE /schedules/:id(.:format)                 schedules#destroy
#                   landings GET    /landings(.:format)                      landings#index
#                            POST   /landings(.:format)                      landings#create
#                new_landing GET    /landings/new(.:format)                  landings#new
#               edit_landing GET    /landings/:id/edit(.:format)             landings#edit
#                    landing GET    /landings/:id(.:format)                  landings#show
#                            PATCH  /landings/:id(.:format)                  landings#update
#                            PUT    /landings/:id(.:format)                  landings#update
#                            DELETE /landings/:id(.:format)                  landings#destroy
#    consulate_lists_country GET    /countries/:id/consulate_lists(.:format) countries#consulate_lists

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  username               :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  display_password       :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  contact                :text
#  email                  :text
#  name                   :string
#  role                   :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable, :recoverable,
         :rememberable, :trackable, :validatable, authentication_keys: [:username]
  
  # validates :email, format: false
  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  validates_presence_of :name, :role

  has_many :users
  has_and_belongs_to_many :countries

  enum role: [ :admin, :consulate ]

  scope :consulates, -> { where(role: "consulate") }

  # after_save :update_user_status
	before_save :encrypt_password, if: :password

  def encrypt_password
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    encrypted_data = crypt.encrypt_and_sign(self.password)
    self.display_password = encrypted_data
  end
  
  def decrypt_password
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    crypt.decrypt_and_verify(display_password) if display_password
  end

  def admin?
    true
  end

  class << self
	  def total_countries_admins
		  Admin.find_by_sql("SELECT count(*) as total FROM admins_countries").last.total
		end

  end
  def can_assesment?
    if self.role.eql?"admin"
      true
    else
      DateTime.now >= Schedule.last.start_consulate_selection - 7.hour and Time.now <= Schedule.last.end_consulate_selection - 7.hour
    end
    
  end

  protected  

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
	before_action :set_var #, only: [:show, :edit, :update, :destroy]
	before_action :verify_user

	def index
		@user.passport_expire = I18n.l(@user.passport_expire, format: :long)  if @user.passport_expire
		@user.dob = I18n.l(@user.dob, format: :long)  if @user.dob
	end
	
	def update
		dashboard_params_edit = dashboard_params
		dashboard_params_edit["dob"] = localize_month(dashboard_params_edit["dob"]).to_date
		dashboard_params_edit["passport_expire"] = localize_month(dashboard_params_edit["passport_expire"]).to_date

		if params["commit"] == "SIMPAN"
			@user.send_profile = false
			dashboard_params_edit["complete"] = false
		else
			dashboard_params_edit["complete"] = true
			dashboard_params_edit["lock"] = true
			@user.send_profile = true
		end
		
	  respond_to do |format|
	    if @user.update(dashboard_params_edit)
	      format.html { redirect_to user_root_path }
	      flash["notice"] = 'Data berhasil diperbarui.'
	      UserMailer.submit_email(@user).deliver_later if params["commit"] == "KIRIM"
	    else
	      format.html { render :index }
	      flash["alert"] = @user.errors.full_messages
	      @user.lock = false
	    end
	  end
	end

	def update_password
		respond_to do |format|
		  if @user.update(dashboard_params)
		    format.html { redirect_to user_root_path }
		    flash["notice"] = 'Data berhasil diperbarui.'
		  else
		    format.html { render :index }
		    flash["alert"] = @user.errors.full_messages
		  end
		end
	end

	# def edit
	# end

	private
	
	def set_var
		@schedule = Schedule.last
	  @user = current_user #User.find(params[:id])
	end

	def verify_user
	  redirect_to root_url if @admin
	  flash["notice"] = "Silahkan mengakses menu Admin untuk mengelola user" if @admin
	end

 	def dashboard_params
    params.require(:user).permit( :name, :country_id, :gender, :passport, :passport_expire, :dob, :admin_id, :skype_id, :password, :password_confirmation,
																	:campus, :majors, :phone, :profession, :lock, :note, :avatar, :passport_image, :complete, :send_profile,
																	to_indonesias_attributes: [:id, :destination, :long, :unit, :_destroy],
																	bipa_courses_attributes: [:id, :location, :long, :unit, :_destroy],
																	score_attributes: [:id, :kind] )
  end

end

app/views/admins/dashboard/_all_usersbackup.html.erb
 <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
        <div class="header">
            <h2>
                SEMUA PESERTA
            </h2>
        </div>
        <div class="body">
            <% if @users.present? %>  
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-data-table-export">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Jenis Lomba</th>
                                <th>Negara</th>
                                <th>KBRI/KJRI</th>
                                <th>Status Kiriman</th>
                                <th>Kelulusan</th>
                                <th>Tahun</th>
                                
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Jenis Lomba</th>
                                <th>Negara</th>
                                <th>KBRI/KJRI</th>
                                <th>Status Kiriman</th>
                                <th>Kelulusan</th>
                                <th>Tahun</th>
                                
                                <th>Aksi</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <% @users.each_with_index do |user, index| %>
                                <tr>
                                    <td><%= index+1 %></td>
                                    <td><%= user.name %></td>
                                    <td><%= show(user.score.kind) %></td>
                                    <td><%= show(user.country.name) %></td>
                                    <td><%= show(user.consulate.name) %></td>
                                    <td><%= show( user.complete.present? ? "Dikirim" : "Belum Dikirim" ) %></td>
                                    <td><%= show(user.win,"Menang","Tidak Menang") %></td>
                                    <td><%= user.year %></td>
                                    <td>
                                        <a href="<%= admins_dashboard_path(user.id) %>" class="btn bg-blue waves-effect" target="blank">Tampilkan</a>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            <% else %>
            <h4 class="text-center">Tidak ada hasil</h4>
            <% end %>
        </div>
    </div>
</div>



<td class="hid"><%= user.to_indonesias.map{|d| [d.destination, d.long, d.unit]}.flatten.to_sentence(last_word_connector:",") if user.to_indonesias
                                     %></td>
                                    <td class="hid"><%= user.bipa_courses.map{|d| [d.location, d.long, d.unit]}.flatten.to_sentence(last_word_connector:",") if user.bipa_courses %></td>
                                    <td class="hid"><%= user.skype_id %></td>
                                    <td><%= show(user.score.kind) %></td>





                                        <% if score.kind.eql?"bercerita"  %>
                                            <table class="hid">
                                               <tr class="hid" width="100">
                                                    <td class="hid">Isi</td>
                                                    <td class="hid"><%= score.content %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Alur</td>
                                                    <td class="hid"><%= score.plot %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Kelancaran</td>
                                                    <td class="hid"><%= score.fluency %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Gestur</td>
                                                    <td class="hid"><%= score.gesture %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Suara</td>
                                                    <td class="hid"><%= score.sound %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Durasi</td>
                                                    <td class="hid"><%= score.duration %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Penampilan</td>
                                                    <td class="hid"><%= score.showing %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Media</td>
                                                    <td class="hid"><%= score.media %></td>
                                               </tr>
                                               <tr class="hid" width="100">
                                                    <td class="hid">Catatan</td>
                                                    <td class="hid"><%= score.note %></td>
                                               </tr>
                                            </table>
                                        <% else %>

                                        <% end %>
                                    <% end %>

app/views/admins/dashboard/_consulate_form.html.erb
<div class="row clearfix">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    TAMBAH KBRI/KJRI
                </h2>
            </div>
            <div class="body">
            <%= form_for(@consulate, url: path) do |f| %>
                <%= f.hidden_field :role, value:"consulate" %>
                <div class="form-group form-float">
                    <div class="form-line">
                        <%= f.text_field :username, class:"form-control", required:true %>
                        <label for="" class="form-label">Username</label>
                    </div>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        <%= f.text_field :password, class:"form-control", required:true %>
                        <label for="" class="form-label">Password</label>
                    </div>
                </div>
                <!-- <div class="form-group form-float">
                    <div class="form-line">
                        <%#= f.text_field :password_confirmation, class:"form-control", required:true %>
                        <label for="" class="form-label">Konfirmasi Password</label>
                    </div>
                </div> -->
                <div class="form-group form-float">
                    <div class="form-line">
                        <%= f.text_field :name, class:"form-control", required:true %>
                        <label for="" class="form-label">Nama</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group form-float">
                        <div class="form-line">
                            <%= select("admin", "country_ids", Country.all.collect {|c| [ c.name, c.id, { selected:
                                if action == "edit" and @consulate.country_ids.include? c.id
                                    true
                                else
                                    false
                                end
                            } ] }, {include_blank:false}, class:"form-control form-control--z-5 show-tick", required:true, multiple:true, "data-live-search": true, "data-title":"Pilih Negara") %>
                        </div>
                    </div>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        <%= f.text_area :email, class:"form-control" %>
                        <label for="" class="form-label">Email</label>
                        
                    </div>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        <%= f.text_area :contact, class:"form-control" %>
                        <label for="" class="form-label">Kontak</label>
                    </div>
                </div>
                <%= f.submit "Simpan", class:"btn btn-primary waves-effect" %>
            <% end %>
            </div>
        </div>
    </div>
</div><!-- ROW -->

app/views/admins/dashboard/consulates.html.erb
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
            LIST KBRI/KJRI 
        </h2>
      </div>
      <div class="body">
        <div class="table-responsive">
          <table class="table table-bordered table-striped table-hover dataTable js-data-table-export">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Username</th>
                <th>Password</th>
                <th>Negara</th>
                <th>Email</th>
                <th>Kontak</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tfoot>
            <tr>
              <th>No</th>
              <th>Nama</th>
              <th>Username</th>
              <th>Password</th>
              <th>Negara</th>
              <th>Email</th>
              <th>Kontak</th>
              <th width="120">Aksi</th>
            </tr>
            </tfoot>
            <tbody>
            <% @consulates.each_with_index do |consulate, index| %>
              <tr>
                <td><%= index+1%></td>
                <td><%= consulate.name %></td>
                <td><%= consulate.username %></td>
                <td><%= consulate.decrypt_password %></td>
                <td><%= consulate.countries.pluck(:name).to_sentence %></td>
                <td><%= consulate.email %></td>
                <td><%= consulate.contact %></td>
                <td>
                <%= link_to "Edit", edit_consulate_path(consulate), class:"btn bg-blue waves-effect" %>
                <%= link_to "Hapus", destroy_consulate_path(consulate), method: :delete, class:"btn bg-blue waves-effect", data: { confirm: "Anda yakin ingin menghapus KBRI/KJRI #{ consulate.name }" } %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ROW -->
<%= render partial: "consulate_form", locals:{ path: create_consulate_path, action: "index"} %>

app/views/admins/dashboard/edit_consulate.html.erb
<%= render partial: "consulate_form", locals:{ path: update_consulate_path, action: "edit" } %>

app/views/admins/dashboard/filters.js.erb
$("#count_pendaftar").text("<%= @user_count %>")
$("#count_peserta").text("<%= @user_complite_count %>")
$("#count_pemenang").text("<%= @user_win_count %>")
$("#all_users").html("<%= j render 'all_users' %> ")
// $.AdminBSB.select.activate();
$('#all_users .card').waitMe("hide");

$.action.tableDataTable.activate();

app/views/admins/dashboard/profile.html.erb
<div class="row">
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Edit Profil</h2>
      </div>
      <div class="body">
        <%= form_for(@admin, url: update_profile_path ) do |f| %>
          <div class="form-group form-float">
              <div class="form-line">
                <%= f.text_field :username, class:"form-control", required:true %>
                  <label class="form-label">Username</label>
              </div>
          </div>
          <div class="form-group form-float">
              <div class="form-line">
                <%= f.text_field :name, class:"form-control", required:true %>
                  <label class="form-label">Nama</label>
              </div>
          </div>
          <div class="form-group form-float">
              <div class="form-line">
                <%= f.text_field :password, class:"form-control", required:true %>
                  <label class="form-label">Password</label>
              </div>
          </div>
          <div class="form-group form-float">
              <div class="form-line">
                <%= f.text_field :email, class:"form-control", required:true %>
                  <label class="form-label">Email</label>
              </div>
          </div>
          <%= f.submit "Simpan", class:"btn btn-primary waves-effect" %>

        <% end %>
        </div>
    </div>
  </div>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>Profil</h2>
      </div>
      <div class="body">
            <div class="table-responsive">
              <table class="table table-hover table-striped dashboard-task-infos">
                <tr>
                  <td>Username</td>
                  <td><%= @admin.username %></td>
                </tr>
                <tr>
                  <td>Nama</td>
                  <td><%= @admin.name %></td>
                </tr>
                <tr>
                  <td>Email</td>
                  <td><%= @admin.email %></td>
                </tr>
                <tr>
                  <td>Password</td>
                  <td><%= @admin.decrypt_password  %></td>
                </tr>
              </table>
            </div>
        </div>
    </div>
  </div>
  
</div>

app/views/admins/dashboard/show.html.erb
<%= render "shared/scoring" %>